# 
FROM python:3.12-alpine

# 
WORKDIR /code

# 
COPY ./containerfiles/reservations/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
# 
COPY ./src/model/reservations /code/src/model/reservations
COPY ./src/model/commons /code/src/model/commons
COPY ./src/model/venues /code/src/model/venues
COPY ./src/model/opinions /code/src/model/opinions
COPY ./src/model/summarizer/ /code/src/model/summarizer
COPY ./src/services/reservations/main.py /code/main.py
COPY ./src/model/communications /code/src/model/communications
# 
CMD ["fastapi", "run", "main.py", "--port", "80"]
