usertypes:
  client: "client"
  anonymous: "anonymous"
  restaurant: "restaurant"

endpoints: 
  - name: "/"
    allowed: ["anonymous"]
  - name: "/users"
    allowed: ["anonymous"]
  - name: "/docs"
    allowed: ["anonymous"]
  - name: "/openapi.json"
    allowed: ["anonymous"]
  - name: "/venues"
    allowed: ["anonymous"]
  - name: "/venues/param"
    allowed: ["anonymous"]

