usertypes:
  client: "client"
  anonymous: "anonymous"
  restaurant: "restaurant"

endpoints: 
  - name: "/"
    allowed: ["anonymous"]
  - name: "/users"
    allowed: ["anonymous"]
  - name: "/docs"
    allowed: ["anonymous"]
  - name: "/openapi.json"
    allowed: ["anonymous"]
  - name: "/venues"
    allowed: ["anonymous"]
  - name: "/venues/param"
    allowed: ["anonymous"]
  - name: "/reservations"
    allowed: ["anonymous"]
  - name: "/reservations/param"
    allowed: ["anonymous"]
  - name: "/reservations/history"
    allowed: ["client"]
  - name: "/reservations/venue"
    allowed: ["restaurant"]
  - name: "/opinions"
    allowed: ["anonymous"]
  - name: "/venue"
    allowed: ["restaurant"]
  - name: "/stats/venue/param"
    allowed: ["restaurant"]
  - name: "/stats/user/param"
    allowed: ["client", "restaurant"] 