# 
FROM python:3.12-alpine

# 
WORKDIR /code

# 
COPY ./containerfiles/communications/requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./src/model/communications /code/src/model/communications
COPY ./src/model/commons /code/src/model/commons

COPY ./src/services/communications/main.py /code/main.py



# 
CMD ["fastapi", "run", "main.py", "--port", "80"]