# 
FROM python:3.12-slim-bullseye

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt
RUN apt update && apt install -y git gcc build-essential python3-dev libgeos-dev

RUN python3 -m pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


# 
COPY ./src/model/users /code/src/model/users
COPY ./src/model/commons /code/src/model/commons

COPY ./src/services/users/main.py /code/main.py



# 
CMD ["fastapi", "run", "main.py", "--port", "80"]
