# 
FROM python:3.12-alpine

# 
WORKDIR /code

# 
COPY ./containerfiles/gateway/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./src/model/gateway /code/src/model/gateway
COPY ./src/model/users /code/src/model/users
COPY ./src/model/commons /code/src/model/commons
COPY ./src/model/venues /code/src/model/venues
COPY ./src/model/reservations /code/src/model/reservations
COPY ./src/model/opinions /code/src/model/opinions
COPY ./src/model/summarizer /code/src/model/summarizer
COPY ./src/model/communications /code/src/model/communications

COPY ./src/services/gateway/main.py /code/main.py



# 
CMD ["fastapi", "run", "main.py", "--port", "80"]
