# 
FROM python:3.12-alpine

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./src/model/gateway /code/src/model/gateway
COPY ./src/model/users /code/src/model/users

COPY ./src/services/gateway/main.py /code/main.py



# 
CMD ["fastapi", "run", "main.py", "--port", "80"]
