name: Deploy containers to container APPs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Log in to Registry
              uses: docker/login-action@v2
              with:
                registry: chefcitoacr.azurecr.io
                username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
                password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}
      
            - name: build-push gateway
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/gateway/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/gateway:latest

            - name: build-push users
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/users/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/users:latest

            - name: build-push venues
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/venues/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/venues:latest
            - name: build-push reservations
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/reservations/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/reservations:latest
            - name: build-push opinions 
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/opinions/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/opinions:latest
            - name: build-push summaries 
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/summaries/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/summaries:latest
            - name: build-push stats 
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/stats/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/stats:latest
            - name: build-push communications 
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/communications/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/communications:latest
            - name: build-push points 
              uses: docker/build-push-action@v3
              with:
                file: containerfiles/points/CONTAINERFILE
                push: true
                tags: chefcitoacr.azurecr.io/points:latest
            

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Short SHA
              run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
            - name: Log in to Azure
              uses: azure/login@v1
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            - name: deploy gateway
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n gateway -g chefcito-rg --revision-suffix ${SHORT_SHA}
            - name: deploy users 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n users -g chefcito-rg --revision-suffix ${SHORT_SHA}
            - name: deploy reservations 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n reservations -g chefcito-rg --revision-suffix ${SHORT_SHA}
            - name: deploy venues 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n venues -g chefcito-rg --revision-suffix ${SHORT_SHA}
            - name: deploy opinions 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n opinions -g chefcito-rg --revision-suffix ${SHORT_SHA}
            - name: deploy summaries 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n summaries -g chefcito-rg --revision-suffix ${SHORT_SHA}
            - name: deploy stats 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n stats -g chefcito-rg --revision-suffix ${SHORT_SHA}
               
            - name: deploy communications 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n communications -g chefcito-rg --revision-suffix ${SHORT_SHA}
               
            - name: deploy points 
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az containerapp revision copy -n points -g chefcito-rg --revision-suffix ${SHORT_SHA}
            
