# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and push containers to staging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest_asyncio testcontainers
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
            registry: chefcitoacr.azurecr.io
            username: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
            password: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}
      
      - name: build-push gateway
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/gateway/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/gateway:latest

      - name: build-push users
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/users/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/users:latest
      
      - name: build-push venues 
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/venues/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/venues:latest

      - name: build-push reservations 
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/reservations/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/reservations:latest
    
      - name: build-push opinions 
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/opinions/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/opinions:latest
      - name: build-push summaries 
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/summaries/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/summaries:latest
      - name: build-push stats 
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/stats/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/stats:latest


      - name: build-push communications 
        uses: docker/build-push-action@v3
        with:
          file: containerfiles/communications/CONTAINERFILE
          push: true
          tags: chefcitoacr.azurecr.io/staging/communications:latest


      

